# Generated by Django 3.2.4 on 2021-06-28 01:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BillingData',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('card_number', models.CharField(max_length=19)),
                ('security_code', models.IntegerField()),
                ('expiration_data', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(max_length=7)),
                ('room_details', models.CharField(max_length=200)),
                ('days', models.IntegerField()),
                ('amout', models.FloatField()),
                ('payment_method', models.CharField(max_length=20)),
                ('billing_data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.billingdata')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.client')),
            ],
        ),
    ]
